### ISSUE TITLE
Broken local Demo

### ISSUE THREAD

**Issue by EWhite613** [ciena-frost/ember-frost-icons#26]
The demo of ember-frost-icons when doing `import svgs from 'ember-frost-icons/svgs'`, the demo grabs the file here `ember-frost-icons/addon/svgs.js`. Rather than the one built here https://github.com/ciena-frost/ember-frost-icons/blob/master/index.js#L45 . 

After the commit here https://github.com/ciena-frost/ember-frost-icons/commit/f60a39e568dbb265b88b0c78a8bf1f1714a164e7 the demo breaks. Before this commit this `prototype.write` in brocolli flatiron https://github.com/buschtoens/broccoli-flatiron/blob/master/index.js#L17 would run after the the constructor.  Possibly b/c of the new version of Ember?

The most likely reason for this is that broccoli-writer https://github.com/broccolijs/broccoli-writer is deprecated in favor of broccoli-plugin https://github.com/broccolijs/broccoli-plugin . 

Currently attempting to make flatiron use broccoli-plugin, instead of broccoli-write, to see if there is a difference

**Comment by sglanzer** [comment]
Not sure `writer` vs `plugin` is an issue, but keep us posted.  Have you tried down versioning ember-cli to see if that’s the issue?

**Comment by EWhite613** [comment]
@sglanzer Was just about to try that. Was looking at all the dependents of flatiron and only one consumer is using ember 2.3.0 as the latest (don't even know if it works b/c the repo looks like a WIP).

**Comment by EWhite613** [comment]
@sglanzer `"ember-cli": "2.3.0"` works.

**Comment by sglanzer** [comment]
Ah, so what's the issue? :)

**Comment by EWhite613** [comment]
@sglanzer Pretty sure it's this commit https://github.com/ember-cli/ember-cli/pull/5561/commits/17619b8f949a200122df62b7a14c66ea7e68f932 All the above commit (til release) are just Eslint stuff. Used the commit before this one and it works

**Comment by sglanzer** [comment]
Super - I doubt we'll get support for what we're doing with flatiron, does the problem go away if we remove the test svg file or is it just a general problem for us now?

**Comment by EWhite613** [comment]
@sglanzer If you remove that file it says it cannot import `ember-frost-icons/svgs`, since broccoli-write's prototype `.write` never gets run for whatever reason. Oddly enough though demo works fine on frost guide.

**Comment by sglanzer** [comment]
That's what I don't get, this only is an issue for the in-repo demo and tests, not apps?

**Comment by EWhite613** [comment]
Ya the consumers work fine. Even the remote demo (http://ciena-frost.github.io/ember-frost-icons/) work fine, it's just locally

**Comment by EWhite613** [comment]
This line is what does it: https://github.com/rwjblue/ember-cli/blame/17619b8f949a200122df62b7a14c66ea7e68f932/lib/models/addon.js#L684

**Comment by EWhite613** [comment]
So without the includePattern inputNodes is `_inputNodes": [
    "\/localdisk\/workspace\/ember-frost-icons\/addon"`

whereas after

 ```
 "_inputNodes": [
    {
      "_instantiationStack": "    at BroccoliMergeTrees.Plugin (\/localdisk\/workspace\/ember-frost-icons\/node_modules\/broccoli-plugin\/index.js:7:31)\n    at new BroccoliMergeTrees (\/localdisk\/workspace\/ember-frost-icons\/node_modules\/broccoli-merge-trees\/index.js:29:10)\n    at BroccoliMergeTrees (\/localdisk\/workspace\/ember-frost-icons\/node_modules\/broccoli-merge-trees\/index.js:23:53)\n    at Class.module.exports.treeForAddon (\/localdisk\/workspace\/ember-frost-icons\/index.js:50:14)\n    at Class._treeFor (\/localdisk\/workspace\/ember-cli\/lib\/models\/addon.js:322:31)\n    at Class.treeFor (\/localdisk\/workspace\/ember-cli\/lib\/models\/addon.js:290:19)\n    at \/localdisk\/workspace\/ember-cli\/lib\/broccoli\/ember-app.js:446:20\n    at Array.map (native)\n    at EmberAddon.EmberApp.addonTreesFor (\/localdisk\/workspace\/ember-cli\/lib\/broccoli\/ember-app.js:444:30)\n    at EmberAddon._addonTree (\/localdisk\/workspace\/ember-cli\/lib\/broccoli\/ember-app.js:849:36)",
      "_name": "BroccoliMergeTrees",
      "_baseConstructorCalled": true,
      "_inputNodes": [
        {
          "_directoryPath": "\/localdisk\/workspace\/ember-frost-icons\/addon",
          "_watched": true,
          "_name": "WatchedDir",
          "_instantiationStack": "    at WatchedDir.Directory (\/localdisk\/workspace\/ember-cli\/node_modules\/broccoli-source\/index.js:14:31)\n    at new WatchedDir (\/localdisk\/workspace\/ember-cli\/node_modules\/broccoli-source\/index.js:58:13)\n    at Class.Addon.treeGenerator (\/localdisk\/workspace\/ember-cli\/lib\/models\/addon.js:258:12)\n    at Class._treeFor (\/localdisk\/workspace\/ember-cli\/lib\/models\/addon.js:318:17)\n    at Class.treeFor (\/localdisk\/workspace\/ember-cli\/lib\/models\/addon.js:290:19)\n    at \/localdisk\/workspace\/ember-cli\/lib\/broccoli\/ember-app.js:446:20\n    at Array.map (native)\n    at EmberAddon.EmberApp.addonTreesFor (\/localdisk\/workspace\/ember-cli\/lib\/broccoli\/ember-app.js:444:30)\n    at EmberAddon._addonTree (\/localdisk\/workspace\/ember-cli\/lib\/broccoli\/ember-app.js:849:36)\n    at EmberAddon.EmberApp._processedVendorTree (\/localdisk\/workspace\/ember-cli\/lib\/broccoli\/ember-app.js:894:20)"
        },
        {
          "inputTree": {
            "_instantiationStack": "    at Funnel.Plugin (\/localdisk\/workspace\/ember-frost-icons\/node_modules\/broccoli-plugin\/index.js:7:31)\n    at new Funnel (\/localdisk\/workspace\/ember-frost-icons\/node_modules\/broccoli-funnel\/index.js:44:10)\n    at Class.module.exports.treeForAddon (\/localdisk\/workspace\/ember-frost-icons\/index.js:41:23)\n    at Class._treeFor (\/localdisk\/workspace\/ember-cli\/lib\/models\/addon.js:322:31)\n    at Class.treeFor (\/localdisk\/workspace\/ember-cli\/lib\/models\/addon.js:290:19)\n    at \/localdisk\/workspace\/ember-cli\/lib\/broccoli\/ember-app.js:446:20\n    at Array.map (native)\n    at EmberAddon.EmberApp.addonTreesFor (\/localdisk\/workspace\/ember-cli\/lib\/broccoli\/ember-app.js:444:30)\n    at EmberAddon._addonTree (\/localdisk\/workspace\/ember-cli\/lib\/broccoli\/ember-app.js:849:36)\n    at EmberAddon.EmberApp._processedVendorTree (\/localdisk\/workspace\/ember-cli\/lib\/broccoli\/ember-app.js:894:20)",
            "_name": "Funnel",
            "_baseConstructorCalled": true,
            "_inputNodes": [
              {
                "_instantiationStack": "    at BroccoliMergeTrees.Plugin (\/localdisk\/workspace\/ember-frost-icons\/node_modules\/broccoli-plugin\/index.js:7:31)\n    at new BroccoliMergeTrees (\/localdisk\/workspace\/ember-frost-icons\/node_modules\/broccoli-merge-trees\/index.js:29:10)\n    at BroccoliMergeTrees (\/localdisk\/workspace\/ember-frost-icons\/node_modules\/broccoli-merge-trees\/index.js:23:53)\n    at Class.module.exports.treeForAddon (\/localdisk\/workspace\/ember-frost-icons\/index.js:41:34)\n    at Class._treeFor (\/localdisk\/workspace\/ember-cli\/lib\/models\/addon.js:322:31)\n    at Class.treeFor (\/localdisk\/workspace\/ember-cli\/lib\/models\/addon.js:290:19)\n    at \/localdisk\/workspace\/ember-cli\/lib\/broccoli\/ember-app.js:446:20\n    at Array.map (native)\n    at EmberAddon.EmberApp.addonTreesFor (\/localdisk\/workspace\/ember-cli\/lib\/broccoli\/ember-app.js:444:30)\n    at EmberAddon._addonTree (\/localdisk\/workspace\/ember-cli\/lib\/broccoli\/ember-app.js:849:36)",
                "_name": "BroccoliMergeTrees",
                "_baseConstructorCalled": true,
                "_inputNodes": [
                  "\/localdisk\/workspace\/ember-frost-icons\/public\/svgs",
                  "\/localdisk\/workspace\/ember-frost-icons\/tests\/dummy\/public\/svgs"
                ],
                "_persistentOutput": true,
                "options": {
                  "overwrite": true
                },
                "_buildCount": 0,
                "_currentTree": {
                  "entries": {
                    "__id__": "relativePath",
                    "size": 0
                  }
                }
              }
            ],
            "_persistentOutput": true,
            "_includeFileCache": {
              
            },
            "_destinationPathCache": {
              
            },
            "_currentTree": {
              "entries": {
                "__id__": "relativePath",
                "size": 0
              }
            },
            "include": [
              {
                
              }
            ],
            "destDir": "\/",
            "count": 0,
            "_matchedWalk": false,
            "_instantiatedStack": "Error\n    at new Funnel (\/localdisk\/workspace\/ember-frost-icons\/node_modules\/broccoli-funnel\/index.js:89:30)\n    at Class.module.exports.treeForAddon (\/localdisk\/workspace\/ember-frost-icons\/index.js:41:23)\n    at Class._treeFor (\/localdisk\/workspace\/ember-cli\/lib\/models\/addon.js:322:31)\n    at Class.treeFor (\/localdisk\/workspace\/ember-cli\/lib\/models\/addon.js:290:19)\n    at \/localdisk\/workspace\/ember-cli\/lib\/broccoli\/ember-app.js:446:20\n    at Array.map (native)\n    at EmberAddon.EmberApp.addonTreesFor (\/localdisk\/workspace\/ember-cli\/lib\/broccoli\/ember-app.js:444:30)\n    at EmberAddon._addonTree (\/localdisk\/workspace\/ember-cli\/lib\/broccoli\/ember-app.js:849:36)\n    at EmberAddon.EmberApp._processedVendorTree (\/localdisk\/workspace\/ember-cli\/lib\/broccoli\/ember-app.js:894:20)\n    at EmberAddon.EmberApp._processedExternalTree (\/localdisk\/workspace\/ember-cli\/lib\/broccoli\/ember-app.js:925:21)"
          },
          "options": {
            "outputFile": "svgs.js",
            "trimExtensions": true
          }
        }
      ],
      "_persistentOutput": true,
      "options": {
        "overwrite": true
      },
      "_buildCount": 0,
      "_currentTree": {
        "entries": {
          "__id__": "relativePath",
          "size": 0
        }
      }
    }
  ],

```

Notice the svgs.js file is there
```
"options": {
            "outputFile": "svgs.js",
            "trimExtensions": true
          }
```

**Comment by sglanzer** [comment]
We can muck with the ember-cli-build.js as much as necessary for this, since it's only for the dummy.  If we need to include our own broccoli funnel or import a dummy file explicitly, that would be fine

**Comment by EWhite613** [comment]
Well this statement

```
if (this._cachedAddonJsFiles) {
	    return this._cachedAddonJsFiles;
	  }
```

is just a time saver. Caching the last run of the function. I say we just submit a PR or raise an issue to remove this if statement ember-cli

**Comment by sglanzer** [comment]
They won't take it, perf is a primary concern - we'll need our own workaround to this

**Comment by EWhite613** [comment]
But this if statement doesn't even make sense in its context. Basically saying if a previous AddonJsFiles is cached return it regardless of whether or not the inputted tree is different

**Comment by sglanzer** [comment]
Ok, if it's a bad cache that's a different matter, go ahead with the PR and mention @rwjblue on it

**Comment by EWhite613** [comment]
Fixed in https://github.com/ember-cli/ember-cli/pull/5867
